# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-06 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(help_text='招聘信息', max_length=100, verbose_name='招聘信息')),
                ('isRemind', models.BooleanField(default=True, help_text='是否提醒', verbose_name='是否提醒')),
                ('lateRemind', models.IntegerField(default=2, help_text='触发天数', verbose_name='触发天数')),
            ],
            options={
                'verbose_name': '刷新信息',
                'verbose_name_plural': '刷新信息',
                'db_table': 'Info',
            },
        ),
    ]
