# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-06 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(help_text='招聘信息', max_length=100, verbose_name='招聘信息')),
                ('isRemind', models.BooleanField(default=True, help_text='是否提醒:1 为提醒，其他值不提醒，建议不提醒的值设置为 0', verbose_name='是否提醒')),
                ('lateRemind', models.IntegerField(default=2, help_text='触发天数', verbose_name='触发天数')),
                ('account', models.CharField(default='1', help_text='账号信息默认:1>广州市银河在线饰品有限公司 2>广州外宝电子商务有限公司', max_length=30, verbose_name='账号信息')),
                ('platform', models.CharField(default='智联', help_text='招聘平台默认:智联,可选参数：前程无忧', max_length=20, verbose_name='招聘平台')),
            ],
            options={
                'verbose_name': '刷新信息',
                'verbose_name_plural': '刷新信息',
                'db_table': 'Info',
            },
        ),
    ]
