# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-07 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='isRemind',
            field=models.BooleanField(default=True, help_text='是否提醒', verbose_name='是否提醒'),
        ),
    ]
