# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-07 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190807_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='info',
            field=models.CharField(max_length=100, verbose_name='招聘信息'),
        ),
        migrations.AlterField(
            model_name='info',
            name='lateRemind',
            field=models.IntegerField(default=2, help_text='这个数值为最大触发提醒的天数，如 10 那么超过 10 天就会提醒', verbose_name='触发天数'),
        ),
    ]
