# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-08 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_info_lastfresh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='关键字信息')),
                ('pageinfo', models.IntegerField(default=0, verbose_name='页数信息')),
                ('plateform', models.CharField(default='智联', max_length=20, verbose_name='平台信息')),
            ],
            options={
                'verbose_name': '排名信息',
                'verbose_name_plural': '排名信息',
                'db_table': 'keyword',
            },
        ),
    ]
