# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-08 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190808_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='posi_nums',
            field=models.IntegerField(default=0, help_text='这个岗位的总共的数量', verbose_name='岗位数量'),
        ),
    ]
