# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-08 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rate_posi_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='platform',
            field=models.CharField(choices=[(1, '智联'), (2, '前程无忧')], default=1, help_text='招聘平台默认:智联,可选参数：前程无忧', max_length=10, verbose_name='招聘平台'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='keyword',
            field=models.CharField(help_text='必填信息', max_length=100, verbose_name='关键字信息'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='pageinfo',
            field=models.IntegerField(default=0, help_text='公司信息最先出现的页数,自己定义的时候需要默认输入0表示不在指定页数', verbose_name='页数信息'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='plateform',
            field=models.CharField(choices=[(1, '智联'), (2, '前程无忧')], default=1, max_length=10, verbose_name='平台信息'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='posi_nums',
            field=models.IntegerField(default=0, help_text='这个岗位的总共的数量，自己定义的时候需要默认输入0表示未查询', verbose_name='岗位数量'),
        ),
    ]
