handler = '张子珏'
receivers = '聂清娜;张子珏'
company_name = '广州银河在线饰品有限公司'
chrome_port = 23355
account_main = 'yhzx151'
# account_from = '2215'
account_from = 'shelly'
download_user = 'shelly'
POST_URL = 'http://hr.gets.com:8989/api/autoOwnerResumeDownload.php?'
POST_URL_AUTO = 'http://hr.gets.com:8989/api/autoOwnerResume.php?'
POST_Search_URL = 'http://hr.gets.com:8989/api/autoInsertResume.php?'
API_GET_URL = 'http://hr.gets.com:8989/api/autoGetKeyword.php?type=download'
POST_URL_COST = 'http://hr.gets.com:8989/api/autoAceUpdateResumeChannel.php?'
# chrome.exe --remote-debugging-port=23355 --user-data-dir="C:\selenum\AutomationProfile"
PASSWORD = 'yhzx2019'
