handler = '陈淼灵'
receivers = '聂清娜;陈淼灵'
company_name = '广州时时美电子商务有限公司'
chrome_port = 23333
account_main = 'ymrj483'
account_from = 'linda'
# account_from = '2114'
download_user = 'linda'
POST_URL = 'http://hr.gets.com:8989/api/autoOwnerResumeDownload.php?'
POST_URL_AUTO = 'http://hr.gets.com:8989/api/autoOwnerResume.php?'
POST_Search_URL = 'http://testhr.gets.com:8989/api/autoInsertResume.php?'
API_GET_URL = 'http://testhr.gets.com:8989/api/autoGetKeyword.php?type=download'
POST_URL_COST = 'http://hr.gets.com:8989/api/autoAceUpdateResumeChannel.php?'
